version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: test-fastapi-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: