"""update ingridient DB

Revision ID: 0035fb44e289
Revises: fdf2008fad02
Create Date: 2024-10-11 17:48:14.730093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0035fb44e289'
down_revision: Union[str, None] = 'fdf2008fad02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('value_type_id', sa.Integer(), nullable=True))
    op.add_column('ingredient', sa.Column('name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ingredient', 'product_value_type', ['value_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'name')
    op.drop_column('ingredient', 'value_type_id')
    # ### end Alembic commands ###
