"""add new DBs

Revision ID: 0c259fe68902
Revises: 7dc46a1f8d66
Create Date: 2024-10-06 22:25:16.303491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c259fe68902'
down_revision: Union[str, None] = '7dc46a1f8d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey'),
    sa.UniqueConstraint('title', name='item_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ingredient',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='ingredient_item_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='ingredient_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingredient_pkey')
    )
    # ### end Alembic commands ###
