"""add event DBs

Revision ID: 1ce7e9d1ff32
Revises: b246fbbb2ddb
Create Date: 2024-10-07 12:11:27.160727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce7e9d1ff32'
down_revision: Union[str, None] = 'b246fbbb2ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('add', 'reduce', name='action'), nullable=False),
    sa.Column('action_value', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_card',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contrast', sa.Enum('greater_than', 'less_than', 'equal_to', 'divisible_by', name='contrast'), nullable=False),
    sa.Column('contrast_value', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benefit_event',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('benefit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'benefit_id')
    )
    op.create_table('criterion_event',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('criterion_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'criterion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criterion_event')
    op.drop_table('benefit_event')
    op.drop_table('event')
    op.drop_table('criterion')
    op.drop_table('bonus_card')
    op.drop_table('benefit')
    # ### end Alembic commands ###
