"""update item DB

Revision ID: 1e749dff35be
Revises: d0b7e7a061de
Create Date: 2024-10-11 10:20:01.500559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e749dff35be'
down_revision: Union[str, None] = 'd0b7e7a061de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('actualise_cost', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('cost', sa.Double(), nullable=True))
    op.add_column('profile', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'phone')
    op.drop_column('item', 'cost')
    op.drop_column('item', 'actualise_cost')
    # ### end Alembic commands ###
