from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4447ed3be586'
down_revision: Union[str, None] = '1ce7e9d1ff32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем новую таблицу profile, которая заменяет таблицу user

    # Обновляем таблицу bonus_card, добавляем колонку phone и меняем внешний ключ на profile
    op.add_column('bonus_card', sa.Column('phone', sa.String(length=20), nullable=False))
    op.alter_column('bonus_card', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('bonus_card_user_id_fkey', 'bonus_card', type_='foreignkey')
    op.create_foreign_key(None, 'bonus_card', 'profile', ['user_id'], ['id'])

    # Обновляем таблицу comment_user, меняем внешний ключ на profile
    op.drop_constraint('comment_user_user_id_fkey', 'comment_user', type_='foreignkey')
    op.create_foreign_key(None, 'comment_user', 'profile', ['user_id'], ['id'])

    # Добавляем колонку is_active в таблицу event
    op.add_column('event', sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем колонку is_active из таблицы event
    op.drop_column('event', 'is_active')

    # Восстанавливаем внешние ключи и структуру таблиц, связанные с user
    op.drop_constraint(None, 'comment_user', type_='foreignkey')
    op.create_foreign_key('comment_user_user_id_fkey', 'comment_user', 'user', ['user_id'], ['id'])

    op.drop_constraint(None, 'bonus_card', type_='foreignkey')
    op.create_foreign_key('bonus_card_user_id_fkey', 'bonus_card', 'user', ['user_id'], ['id'])
    op.alter_column('bonus_card', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bonus_card', 'phone')


    # ### end Alembic commands ###
