"""update card and akce DBs

Revision ID: 5153c2061b97
Revises: 1791723e1d01
Create Date: 2024-10-13 17:03:27.267116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5153c2061b97'
down_revision: Union[str, None] = '1791723e1d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus_card', sa.Column('used_points', sa.Integer(), nullable=True))
    op.alter_column('order', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bonus_card', 'used_points')
    # ### end Alembic commands ###
