"""add alergern, comment and event DBs

Revision ID: 7dc46a1f8d66
Revises: ea10e60530d4
Create Date: 2024-10-06 21:48:40.377930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc46a1f8d66'
down_revision: Union[str, None] = 'ea10e60530d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
