"""change table names

Revision ID: b13e27d04369
Revises: 212ab4254717
Create Date: 2024-10-05 20:27:55.486653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13e27d04369'
down_revision: Union[str, None] = '212ab4254717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop foreign keys first
    op.drop_constraint('shop_product_shop_id_fkey', 'shop_product', type_='foreignkey')
    op.drop_constraint('shop_product_product_id_fkey', 'shop_product', type_='foreignkey')

    # Create new tables
    op.create_table('item',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )

    op.create_table('shop',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table('product',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('value', sa.Double(), nullable=False),
        sa.Column('value_type_id', sa.Integer(), nullable=False),
        sa.Column('cost_per_one', sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(['value_type_id'], ['product_value_type.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table('ingredient',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Double(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Drop old tables now
    op.drop_table('ingredients')
    op.drop_table('shops')
    op.drop_table('products')
    op.drop_table('items')

    # Recreate the foreign keys on the new tables
    op.create_foreign_key(None, 'shop_product', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'shop_product', 'shop', ['shop_id'], ['id'])



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_product', type_='foreignkey')
    op.drop_constraint(None, 'shop_product', type_='foreignkey')
    op.create_foreign_key('shop_product_shop_id_fkey', 'shop_product', 'shops', ['shop_id'], ['id'])
    op.create_foreign_key('shop_product_product_id_fkey', 'shop_product', 'products', ['product_id'], ['id'])
    op.create_table('items',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey'),
    sa.UniqueConstraint('title', name='items_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('value_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_per_one', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['value_type_id'], ['product_value_type.id'], name='products_value_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('name', name='products_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shops_pkey'),
    sa.UniqueConstraint('name', name='shops_name_key')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='ingredients_item_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='ingredients_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingredients_pkey')
    )
    op.drop_table('ingredient')
    op.drop_table('product')
    op.drop_table('shop')
    op.drop_table('item')
    # ### end Alembic commands ###
